namespace Pzl.Aoc.Puzzles.Aoc2025.Aoc202507;

public class Aoc202507Tests
{
    private const string Input = """
                                 .......S.......
                                 ...............
                                 .......^.......
                                 ...............
                                 ......^.^......
                                 ...............
                                 .....^.^.^.....
                                 ...............
                                 ....^.^...^....
                                 ...............
                                 ...^.^...^.^...
                                 ...............
                                 ..^...^.....^..
                                 ...............
                                 .^.^.^.^.^...^.
                                 ...............
                                 """;

    [Fact]
    public void Part1() => Sut.Part1(Input).Answer.Should().Be("21");

    [Fact]
    public void Part2() => Sut.Part2(Input).Answer.Should().Be("40");

    private static Aoc202507 Sut => new();
}