using Pzl.Aoc.Puzzles.Aoc2025;

namespace Tests.Aoc.Aoc2025;

public class Aoc202507Tests
{
    private const string Input = """
                                 .......S.......
                                 ...............
                                 .......^.......
                                 ...............
                                 ......^.^......
                                 ...............
                                 .....^.^.^.....
                                 ...............
                                 ....^.^...^....
                                 ...............
                                 ...^.^...^.^...
                                 ...............
                                 ..^...^.....^..
                                 ...............
                                 .^.^.^.^.^...^.
                                 ...............
                                 """;

    [Fact]
    public void Part1() => Sut.Part1(Input).Should().Be(21);

    [Fact]
    public void Part2() => Sut.Part2(Input).Should().Be(40);

    private static Aoc202507 Sut => new();
}