using Pzl.Tools.Grids.Grids2d;

namespace Pzl.Everybody.Puzzles.Ece2025.Ece202520;

public class Ece202520Tests
{
    [Fact]
    public void Part1_1()
    {
        const string input = """
                             T#TTT###T##
                             .##TT#TT##.
                             ..T###T#T..
                             ...##TT#...
                             ....T##....
                             .....#.....
                             """;

        Sut.Part1(input).Answer.Should().Be("7");
    }
    
    [Fact]
    public void Part1_2()
    {
        const string input = """
                             T#T#T#T#T#T
                             .T#T#T#T#T.
                             ..T#T#T#T..
                             ...T#T#T...
                             ....T#T....
                             .....T.....
                             """;

        Sut.Part1(input).Answer.Should().Be("0");
    }
    
    [Fact]
    public void Part1_3()
    {
        const string input = """
                             T#T#T#T#T#T
                             .#T#T#T#T#.
                             ..#T###T#..
                             ...##T##...
                             ....#T#....
                             .....#.....
                             """;

        Sut.Part1(input).Answer.Should().Be("0");
    }

    [Fact]
    public void Part2()
    {
        const string input = """
                             TTTTTTTTTTTTTTTTT
                             .TTTT#T#T#TTTTTT.
                             ..TT#TTTETT#TTT..
                             ...TT#T#TTT#TT...
                             ....TTT#T#TTT....
                             .....TTTTTT#.....
                             ......TT#TT......
                             .......#TT.......
                             ........S........
                             """;

        Sut.Part2(input).Answer.Should().Be("32");
    }

    [Fact]
    public void Part3_Rotate()
    {
        const string state1 = """
                              T####T#TTT##T##T#T#
                              .T#####TTTT##TTT##.
                              ..TTTT#T###TTTT#T..
                              ...T#TTT#TTTTT##...
                              ....#TT##T#T##T....
                              .....#TT####T#.....
                              ......T#TT#T#......
                              .......T#TTT.......
                              ........TT#........
                              .........T.........
                              """;

        const string state2 = """
                              TTT#T#TT#T##TTT#T#T
                              .#TTTT#T#TTTTT####.
                              ..TT###T##TT###T#..
                              ...#T#T#TT##TTT#...
                              ....###TTT#TTTT....
                              .....T#TTT####.....
                              ......##TTT#T......
                              .......T#TT#.......
                              ........#T#........
                              .........#.........
                              """;

        const string state3 = """
                              #T##T###T##T#TTT#TT
                              .#TTTTTTT#T###TT#T.
                              ..##T#TTTT#T##T#T..
                              ...T##T##T###TTT...
                              ....#TTT#TTTTT#....
                              .....TTT##TT##.....
                              ......#T##TTT......
                              .......####T.......
                              ........##T........
                              .........T.........
                              """;

        var grid = GridBuilder.BuildCharGrid(state1);
        grid = Sut.Rotate(grid);
        grid.Print().Should().Be(state2);
        grid = Sut.Rotate(grid);
        grid.Print().Should().Be(state3);
        grid = Sut.Rotate(grid);
        grid.Print().Should().Be(state1);
    }
    
    [Fact]
    public void Part3()
    {
        const string input = """
                             T####T#TTT##T##T#T#
                             .T#####TTTT##TTT##.
                             ..TTTT#T###TTTT#T..
                             ...T#TTT#ETTTT##...
                             ....#TT##T#T##T....
                             .....#TT####T#.....
                             ......T#TT#T#......
                             .......T#TTT.......
                             ........TT#........
                             .........S.........
                             """;

        Sut.Part3(input).Answer.Should().Be("23");
    }

    private static Ece202520 Sut => new();
}