using Pzl.Aoc.Puzzles.Aoc2024;

namespace Tests.Aoc.Aoc2024;

public class Aoc202408Tests : PuzzleTest<Aoc202408>
{
    private const string Input = """
                                 ............
                                 ........0...
                                 .....0......
                                 .......0....
                                 ....0.......
                                 ......A.....
                                 ............
                                 ............
                                 ........A...
                                 .........A..
                                 ............
                                 ............
                                 """;

    [Fact]
    public void Part1()
    {
        Sut.Part1(Input).Should().Be(14);
    }

    [Fact]
    public void Part2()
    {
        Sut.Part2(Input).Should().Be(34);
    }

}