namespace Pzl.Tools.Ocr;

public class OcrLargeFontTests
{
    [Theory]
    [InlineData(InputB, 'B')]
    [InlineData(InputG, 'G')]
    [InlineData(InputH, 'H')]
    [InlineData(InputK, 'K')]
    [InlineData(InputP, 'P')]
    [InlineData(InputR, 'R')]
    [InlineData(InputSpace, ' ')]
    public void TestReadLetter(string input, char expected) =>
        OcrLargeFont.ReadLetter(input)
            .Should().Be(expected);

    [Fact]
    public void TestReadString() =>
        OcrLargeFont.ReadString(Input)
            .Should().Be("HRP");

    private const string Input = """
                                 #....#..#####...#####...
                                 #....#..#....#..#....#..
                                 #....#..#....#..#....#..
                                 #....#..#....#..#....#..
                                 ######..#####...#####...
                                 #....#..#..#....#.......
                                 #....#..#...#...#.......
                                 #....#..#...#...#.......
                                 #....#..#....#..#.......
                                 #....#..#....#..#.......
                                 """;

    private const string InputB = """
                                  #####...
                                  #....#..
                                  #....#..
                                  #....#..
                                  #####...
                                  #....#..
                                  #....#..
                                  #....#..
                                  #....#..
                                  #####...
                                  """;

    private const string InputG = """
                                  .####...
                                  #....#..
                                  #.......
                                  #.......
                                  #.......
                                  #..###..
                                  #....#..
                                  #....#..
                                  #...##..
                                  .###.#..
                                  """;

    private const string InputH = """
                                  #....#..
                                  #....#..
                                  #....#..
                                  #....#..
                                  ######..
                                  #....#..
                                  #....#..
                                  #....#..
                                  #....#..
                                  #....#..
                                  """;

    private const string InputK = """
                                  #....#..
                                  #...#...
                                  #..#....
                                  #.#.....
                                  ##......
                                  ##......
                                  #.#.....
                                  #..#....
                                  #...#...
                                  #....#..
                                  """;

    private const string InputP = """
                                  #####...
                                  #....#..
                                  #....#..
                                  #....#..
                                  #####...
                                  #.......
                                  #.......
                                  #.......
                                  #.......
                                  #.......
                                  """;

    private const string InputR = """
                                  #####...
                                  #....#..
                                  #....#..
                                  #....#..
                                  #####...
                                  #..#....
                                  #...#...
                                  #...#...
                                  #....#..
                                  #....#..
                                  """;

    private const string InputSpace = """
                                      ........
                                      ........
                                      ........
                                      ........
                                      ........
                                      ........
                                      ........
                                      ........
                                      ........
                                      ........
                                      """;
}